### ISSUE TITLE
Cannot install extension on windows

### ISSUE THREAD

**Issue by lawsontaylor** [Spark3000/Oceanic-Park#1]
Microsoft Windows [Version 10.0.17134.706]
VSCode v1.33.1
Electron 3.1.6
Node 10.2.0

I cloned the repo to my '/.vscode/extensions' directory with my other extension but It doesn't appear in Extensions and is not active.
Please help Mr. Sean
Your colour scheme is very Bagus.

**Comment by lawsontaylor** [comment]
Nevermind :rocket: https://marketplace.visualstudio.com/items?itemName=FrankJames.oceanic-park

**Comment by seanonthenet** [comment]
Published for your convenience https://marketplace.visualstudio.com/items?itemName=Parklife.oceanic-park
